language: python

python: 2.7

env:
  - TOXENV=py27-17
  - TOXENV=py27-18
  - TOXENV=py27-19
  - TOXENV=py34-17
  - TOXENV=py34-18
  - TOXENV=py34-19
  - TOXENV=py35-18
  - TOXENV=py35-19

install:
  - pip install --upgrade pip setuptools tox virtualenv coveralls

script:
  - tox

after_success: coveralls
